name: 02 - Workflow Events

on: 
    push:
    pull_request: 
    schedule: 
      - cron: '*/5 * * * *'
    workflow_dispatch: 

jobs:
    echo:
        runs-on: ubuntu-latest 
        steps:
            - name: Triggering Event
              run: echo "This workflow was triggered by ${{ github.Event_name}} event."
