name: 'custom GITHUB_Secrets var Demo'

on:  workflow_dispatch

jobs:
  custom_GITHUB_ENV:
    runs-on: ubuntu-latest 
    steps:
    - name: Set the value
      id: step_one
      run: |
        echo "My secret is stored in Repo Secret Variable named Top Secert"

    - name: Use the value
      id: step_two
      run: |
        echo "My secret value is ${{ secret.top_secrte }}"

